#! /usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Simple wrapper script around the Reports bot task runner.

To run a task located at 'tasks/foobar.py':

    ./run foobar

For detailed command-line arguments:

    ./run --help
"""

from os import environ, path

root = path.dirname(__file__)

task_dir = path.join(root, "tasks")
config_dir = path.join(root, "config")
log_dir = path.join(root, "logs")

environ["PYWIKIBOT2_DIR"] = config_dir

from reportsbot.cli import run

run(task_dir, config_dir, log_dir)
